name: CI/CD Build and publish to Azure

env:
  AZURE_WEBAPP_NAME: orders-api-recruitment-task
  AZURE_WEBAPP_PACKAGE_PATH: "./src/API/publish"
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: "OrdersApi.sln"
  API_PATH: "./src/API"
  PUBLISH_DIR: "./publish"

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build 
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ${{ env.API_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      

